### ISSUE TITLE
NameError: name 'temp_path' is not defined

### ISSUE THREAD

**Issue by ipoom-jeong** [NetApp/SQL_Storage_Benchmark#2]
Hello,

When I tried to setup the database using setupssb.py (it is setup3sb.py actually), I got error:
"NameError: name 'temp_path' is not defined"
even though I already set the temp path.

My command is: 
python3 /home/_user_/bench/SQL_Storage_Benchmark/setup3sb.py -s mysql -d 200GB -ut 10 -D ssbtest -H localhost -l _user_ -p _password_ -t /home/_user_

Console:
G
26214400.0
*****************************************************************************************************
* Database Size:200GB
* Total Number of Rows in Database:26214400.0
* Number of Rows Per User: 2621440
*****************************************************************************************************
****************************************************************************************************
Attempting to connect to the specified MySql Server
****************************************************************************************************
**********************************************************************************************
MySql Server connection was successful!
**********************************************************************************************
Creating Database
*****************************************************************************************************
*Creating Index for user 1                                                                         *
*****************************************************************************************************
*****************************************************************************************************
*Creating Index for user 2                                                                         *
*****************************************************************************************************
*****************************************************************************************************
*Creating Index for user 3                                                                         *
*****************************************************************************************************
*****************************************************************************************************
*Creating Index for user 4                                                                         *
*****************************************************************************************************
*****************************************************************************************************
*Creating Index for user 5                                                                         *
*****************************************************************************************************
*****************************************************************************************************
*Creating Index for user 6                                                                         *
*****************************************************************************************************
*****************************************************************************************************
*Creating Index for user 7                                                                         *
*****************************************************************************************************
*****************************************************************************************************
*Creating Index for user 8                                                                         *
*****************************************************************************************************
*****************************************************************************************************
*Creating Index for user 9                                                                         *
*****************************************************************************************************
*****************************************************************************************************
*Creating Index for user 10                                                                         *
*****************************************************************************************************
**********************************************************************************************
Creating Data and loading tables for user 1 out of 10 users.                                *
**********************************************************************************************
Traceback (most recent call last):
  File "/home/_user_/bench/SQL_Storage_Benchmark/setup3sb.py", line 374, in <module>
    main()
  File "/home/_ipoom_/bench/SQL_Storage_Benchmark/setup3sb.py", line 335, in main
    args = "python database_loader.py {} {} {} {} {} {} {} {} {}".format(users,user_number,rows_per_user,sql_version,database_name,host,username,password,temp_path)
NameError: name 'temp_path' is not defined

Any ideas on this issue?

**Comment by rpratt-eng1** [comment]
looked into the issue. Setup passes 9 parameters, including the temp_path parameter for MySql into the Database loader program, however, the temp_path variable is missing for the Database loader program. As a quick fix, you can open the Database loader program and starting on line 9, you'll see a list of parameters expected similar to users=sys.argv[1]. Just add temp_path = sys.argv[9] on line 17 under password = sys.argv[8]. 

Thanks.

**Comment by ipoom-jeong** [comment]
Thank you for your reply.

As a matter of fact, it is not the issue with database_loader.py.

I should have changed the lines 335 and 354 of setup3sb.py: temp_path --> abs_path since temp_path variable is not defined with mysql environment.

After this change, it moves forward further, but I met another error during loading the database tables, as follows:

**********************************************************************************************
Creating Data and loading tables for user 1 out of 10 users.                                *
**********************************************************************************************
**********************************************************************************************
Creating Data and loading tables for user 2 out of 10 users.                                *
**********************************************************************************************
**********************************************************************************************
Creating Data and loading tables for user 3 out of 10 users.                                *
**********************************************************************************************
**********************************************************************************************
Creating Data and loading tables for user 4 out of 10 users.                                *
**********************************************************************************************
Writing out data file /home/ipoom/ssd_raid0/working_dir/ssb/bulk_data_user_1_1_100000_mysql.csv
**********************************************************************************************
Creating Data and loading tables for user 5 out of 10 users.                                *
**********************************************************************************************
Writing out data file /home/ipoom/ssd_raid0/working_dir/ssb/bulk_data_user_2_1_100000_mysql.csv
Writing out data file /home/ipoom/ssd_raid0/working_dir/ssb/bulk_data_user_3_1_100000_mysql.csv
Writing out data file /home/ipoom/ssd_raid0/working_dir/ssb/bulk_data_user_4_1_100000_mysql.csv
Writing out data file /home/ipoom/ssd_raid0/working_dir/ssb/bulk_data_user_5_1_100000_mysql.csv
Traceback (most recent call last):
  File "database_loader.py", line 221, in <module>
    main()
  File "database_loader.py", line 217, in main
    mysql_load_database_tables()
  File "database_loader.py", line 181, in mysql_load_database_tables
    load_connect = mysql.connector.connect(**connect_string)
  File "/home/ipoom/.local/lib/python3.8/site-packages/mysql/connector/pooling.py", line 286, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/home/ipoom/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 101, in __init__
    self.connect(**kwargs)
  File "/home/ipoom/.local/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 1108, in connect
    self._open_connection()
  File "/home/ipoom/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 268, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
TypeError: an integer is required (got type str)

This might be due to the args for connect, but I'm not sure which part is the problem.

This is my command line: 
python3 setup3sb.py -s mysql -d 200GB -ut 10 -D ssbtest -H localhost -l _user_ -p _password_ -t /home/_user_working_dir/

Do you have any comment on this?
